package com.shvcs.cleaner.viewmodel

import android.app.Application
import android.content.Context
import androidx.lifecycle.AndroidViewModel
import androidx.lifecycle.viewModelScope
import android.bluetooth.BluetoothDevice
import com.shvcs.cleaner.elm.ElmBluetoothManager
import com.shvcs.cleaner.elm.ElmManager
import com.shvcs.cleaner.elm.ElmWifiManager
import com.shvcs.cleaner.elm.OBDProtocol
import com.shvcs.cleaner.elm.UdsResponse
import com.shvcs.cleaner.elm.DtcParser
import com.shvcs.cleaner.elm.DtcScanner
import com.shvcs.cleaner.elm.SeedKeyGenerator
import com.shvcs.cleaner.elm.BatteryDataParser
import com.shvcs.cleaner.elm.BatteryScanner
import com.shvcs.cleaner.elm.LiveMonitor
import com.shvcs.cleaner.data.ScanResult
import com.shvcs.cleaner.data.ScanResultDatabase
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import org.json.JSONObject

enum class ConnectionState {
    DISCONNECTED, CONNECTING, CONNECTED, RUNNING, AWAITING_KEY, UNLOCKING, SUCCESS, ERROR
}

enum class ConnectionMode { WIFI, BLUETOOTH }

data class AppState(
    val connectionState: ConnectionState = ConnectionState.DISCONNECTED,
    val vin: String = "—",
    val voltage: String = "—",
    val seed: String = "—",
    val progress: Float = 0f,
    val progressStep: String = "",
    val totalSteps: Int = 0,
    val currentStep: Int = 0,
    val logs: List<String> = emptyList(),
    val errorMessage: String? = null,
    val elmIp: String = ElmWifiManager.DEFAULT_IP,
    val elmPort: Int = ElmWifiManager.DEFAULT_PORT,
    val savedKeys: List<String> = emptyList(),
    /** Human-readable summary of the last ECU response */
    val ecuResponse: String? = null,
    /** Color category for the ECU response display */
    val ecuResponseCategory: UdsResponse.Category = UdsResponse.Category.NEUTRAL,
    /** List of DTCs read from the ECU */
    val dtcList: List<DtcParser.DtcCode> = emptyList(),
    /** Whether a DTC read/clear operation is in progress */
    val isDtcLoading: Boolean = false,
    /** Seed → Key mappings configured in Settings */
    val seedKeyMap: Map<String, String> = emptyMap(),
    /** Key automatically calculated from the Voltage reverse-engineered DB */
    val autoGeneratedKey: String? = null,
    /** True when the AWAITING_KEY state is for testing the key instead of clearing */
    val pendingKeyTest: Boolean = false,
    /** True when the AWAITING_KEY state is for DTC clear (vs SHVCS clear) */
    val pendingDtcClear: Boolean = false,
    /** Console history: list of (command, response) pairs */
    val consoleHistory: List<Pair<String, String>> = emptyList(),
    /** ECUs discovered during init scan */
    val discoveredEcus: List<OBDProtocol.DiscoveredEcu> = emptyList(),
    /** Battery data from the latest scan */
    val batteryData: BatteryDataParser.BatteryData? = null,
    /** Whether a battery scan is in progress */
    val isBatteryScanLoading: Boolean = false,
    /** Whether live monitoring is active */
    val isMonitoring: Boolean = false,
    /** Live monitoring data history (for charts) */
    val liveHistory: List<LiveMonitor.LiveDataPoint> = emptyList(),
    /** Persisted scan history from Room DB */
    val scanHistory: List<ScanResult> = emptyList(),
    /** Compare tab: selected scan A */
    val compareScanA: ScanResult? = null,
    /** Compare tab: selected scan B */
    val compareScanB: ScanResult? = null,
    /** Currently selected navigation tab */
    val selectedTab: Int = 0,
    /** Multi-module DTC scan result */
    val dtcScanResult: DtcScanner.DtcScanResult? = null,
    /** Module currently being cleared (null if none) */
    val clearingModuleId: String? = null,
    /** Connection mode: WiFi or Bluetooth */
    val connectionMode: ConnectionMode = ConnectionMode.WIFI,
    /** Connected Bluetooth device name (if applicable) */
    val btDeviceName: String? = null,
)

class MainViewModel(application: Application) : AndroidViewModel(application) {

    private val wifiElm = ElmWifiManager()
    private val btElm = ElmBluetoothManager()
    private var elm: ElmManager = wifiElm
    private val _state = MutableStateFlow(AppState())
    val state: StateFlow<AppState> = _state.asStateFlow()
    private var liveJob: Job? = null
    private val db = ScanResultDatabase.getInstance(application)

    private val prefs = application.getSharedPreferences("shvcs_settings", Context.MODE_PRIVATE)

    init {
        SeedKeyGenerator.initialize(application)
        _state.value = _state.value.copy(
            elmIp = prefs.getString("elm_ip", ElmWifiManager.DEFAULT_IP) ?: ElmWifiManager.DEFAULT_IP,
            elmPort = prefs.getInt("elm_port", ElmWifiManager.DEFAULT_PORT),
            savedKeys = loadSavedKeys(),
            seedKeyMap = loadSeedKeyMap()
        )
        // Collect scan history from Room
        viewModelScope.launch {
            db.scanResultDao().getAllDesc().collect { scans ->
                _state.value = _state.value.copy(scanHistory = scans)
            }
        }
    }

    fun saveSettings(ip: String, port: Int) {
        prefs.edit()
            .putString("elm_ip", ip)
            .putInt("elm_port", port)
            .apply()
        _state.value = _state.value.copy(elmIp = ip, elmPort = port)
    }

    /**
     * Save a seed → key mapping.
     */
    fun saveSeedKeyMapping(seed: String, key: String) {
        val upperSeed = seed.uppercase()
        val upperKey = key.uppercase()
        val map = _state.value.seedKeyMap.toMutableMap()
        map[upperSeed] = upperKey
        _state.value = _state.value.copy(seedKeyMap = map)
        persistSeedKeyMap(map)
    }

    /**
     * Delete a seed → key mapping.
     */
    fun deleteSeedKeyMapping(seed: String) {
        val map = _state.value.seedKeyMap.toMutableMap()
        map.remove(seed.uppercase())
        _state.value = _state.value.copy(seedKeyMap = map)
        persistSeedKeyMap(map)
    }

    fun connect() {
        viewModelScope.launch {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.CONNECTING,
                logs = _state.value.logs + "Connecting to ${_state.value.elmIp}:${_state.value.elmPort}...",
                errorMessage = null
            )
            val result = wifiElm.connect(_state.value.elmIp, _state.value.elmPort)
            result.onSuccess {
                _state.value = _state.value.copy(
                    logs = _state.value.logs + "✓ TCP connected to ELM327"
                )

                // Auto-init and read vehicle data
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.RUNNING,
                    progressStep = "Initializing..."
                )
                val initOk = OBDProtocol.executeInitAndReadData(elm, createListener())

                if (initOk) {
                    _state.value = _state.value.copy(
                        connectionState = ConnectionState.CONNECTED,
                        progress = 1f,
                        progressStep = "Ready"
                    )

                    // Auto-scan battery data (kept as requested)
                    scanBattery()
                } else {
                    // TCP is still connected, but init failed — show as CONNECTED with error
                    _state.value = _state.value.copy(
                        connectionState = ConnectionState.CONNECTED,
                        progress = 0f,
                        progressStep = "Init failed",
                        errorMessage = "ELM327 initialization failed — try again or check connection"
                    )
                }
            }.onFailure { e ->
                // TCP connection failed — go back to DISCONNECTED so the UI shows CONNECT
                elm.disconnect()
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.DISCONNECTED,
                    logs = _state.value.logs + "✗ Connection failed: ${e.message}",
                    errorMessage = "Connection failed: ${e.message}"
                )
            }
        }
    }

    /**
     * Connect to an ELM327 dongle via Bluetooth.
     */
    @android.annotation.SuppressLint("MissingPermission")
    fun connectBluetooth(device: BluetoothDevice) {
        elm = btElm
        viewModelScope.launch {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.CONNECTING,
                connectionMode = ConnectionMode.BLUETOOTH,
                btDeviceName = device.name ?: device.address,
                logs = _state.value.logs + "Connecting via Bluetooth to ${device.name ?: device.address}...",
                errorMessage = null
            )
            val result = btElm.connect(device)
            result.onSuccess {
                _state.value = _state.value.copy(
                    logs = _state.value.logs + "✓ Bluetooth connected to ELM327"
                )

                // Auto-init and read vehicle data
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.RUNNING,
                    progressStep = "Initializing..."
                )
                val initOk = OBDProtocol.executeInitAndReadData(elm, createListener())

                if (initOk) {
                    _state.value = _state.value.copy(
                        connectionState = ConnectionState.CONNECTED,
                        progress = 1f,
                        progressStep = "Ready"
                    )
                    scanBattery()
                } else {
                    _state.value = _state.value.copy(
                        connectionState = ConnectionState.CONNECTED,
                        progress = 0f,
                        progressStep = "Init failed",
                        errorMessage = "ELM327 initialization failed — try again or check connection"
                    )
                }
            }.onFailure { e ->
                elm.disconnect()
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.DISCONNECTED,
                    logs = _state.value.logs + "✗ Bluetooth connection failed: ${e.message}",
                    errorMessage = "Bluetooth failed: ${e.message}"
                )
            }
        }
    }

    /**
     * Set the connection mode (WiFi or Bluetooth) — used before connect.
     */
    fun setConnectionMode(mode: ConnectionMode) {
        elm = when (mode) {
            ConnectionMode.WIFI -> wifiElm
            ConnectionMode.BLUETOOTH -> btElm
        }
        _state.value = _state.value.copy(connectionMode = mode)
    }

    fun disconnect() {
        viewModelScope.launch {
            elm.disconnect()
            _state.value = _state.value.copy(
                connectionState = ConnectionState.DISCONNECTED,
                vin = "—", voltage = "—", seed = "—",
                progress = 0f, progressStep = "",
                currentStep = 0, totalSteps = 0,
                errorMessage = null
            )
        }
    }

    fun startClearSequence(testOnly: Boolean = false) {
        val cs = _state.value.connectionState
        if (cs != ConnectionState.CONNECTED && cs != ConnectionState.SUCCESS && cs != ConnectionState.ERROR) return

        viewModelScope.launch {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.RUNNING,
                progress = 0f,
                seed = "—",
                errorMessage = null,
                ecuResponse = null,
                ecuResponseCategory = UdsResponse.Category.NEUTRAL,
                pendingDtcClear = false,
                pendingKeyTest = testOnly,
                autoGeneratedKey = null,
                logs = _state.value.logs + "" + if (testOnly) "━━━ STARTING KEY TEST SEQUENCE ━━━" else "━━━ STARTING SHVCS CLEAR SEQUENCE ━━━"
            )

            val seed = OBDProtocol.executeUntilSeed(elm, createListener())

            if (seed != null) {
                // Seed received — wait for user key input
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.AWAITING_KEY,
                    progressStep = "Enter security key"
                )
            }
            // If seed is null, listener.onError already set ERROR state
        }
    }

    /**
     * User submits a key from the dialog.
     * Routes to either the SHVCS clear or DTC clear flow depending on pendingDtcClear.
     */
    fun submitKey(key: String) {
        val upperKey = key.uppercase()
        if (!OBDProtocol.isValidKey(upperKey)) {
            _state.value = _state.value.copy(
                errorMessage = "Invalid key. Enter exactly 4 hex characters (0-9, A-F)",
                logs = _state.value.logs + "✗ Invalid key format: $key"
            )
            return
        }

        viewModelScope.launch {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.UNLOCKING,
                errorMessage = null,
                logs = _state.value.logs + "Submitting key: $upperKey"
            )

            if (_state.value.pendingDtcClear) {
                // DTC clear flow: unlock + 14 FF FF FF + re-read
                _state.value = _state.value.copy(isDtcLoading = true)
                val result = OBDProtocol.clearAllDtcsUds(elm, upperKey, createListener())

                when (result) {
                    OBDProtocol.KeySubmitResult.SUCCESS -> {
                        saveKey(upperKey)
                        // Re-read to verify
                        kotlinx.coroutines.delay(1000)
                        OBDProtocol.readAllDtcs(elm, createListener())

                        if (_state.value.dtcList.isEmpty()) {
                            _state.value = _state.value.copy(
                                ecuResponse = "✓ All DTCs cleared!",
                                ecuResponseCategory = UdsResponse.Category.SUCCESS
                            )
                        } else {
                            _state.value = _state.value.copy(
                                ecuResponse = "${_state.value.dtcList.size} DTC(s) remain",
                                ecuResponseCategory = UdsResponse.Category.WARNING
                            )
                        }
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.CONNECTED,
                            isDtcLoading = false,
                            pendingDtcClear = false
                        )
                    }
                    OBDProtocol.KeySubmitResult.INVALID_KEY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Enter security key for DTC clear",
                            isDtcLoading = false
                        )
                    }
                    OBDProtocol.KeySubmitResult.TIME_DELAY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Wait then retry",
                            isDtcLoading = false
                        )
                    }
                    OBDProtocol.KeySubmitResult.MAX_ATTEMPTS -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR,
                            isDtcLoading = false,
                            pendingDtcClear = false
                        )
                    }
                    OBDProtocol.KeySubmitResult.REJECTED -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR,
                            isDtcLoading = false,
                            pendingDtcClear = false
                        )
                    }
                }
            } else if (_state.value.pendingKeyTest) {
                // Key Test flow: unlock ONLY, verify response, disconnect
                val result = OBDProtocol.testKeyValidity(elm, upperKey, createListener())

                when (result) {
                    OBDProtocol.KeySubmitResult.SUCCESS -> {
                        saveKey(upperKey)
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.CONNECTED,
                            pendingKeyTest = false,
                            ecuResponse = "✓ Key accepted by ECU!",
                            ecuResponseCategory = UdsResponse.Category.SUCCESS
                        )
                    }
                    OBDProtocol.KeySubmitResult.INVALID_KEY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Key rejected, try again"
                        )
                    }
                    OBDProtocol.KeySubmitResult.TIME_DELAY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Wait then retry"
                        )
                    }
                    OBDProtocol.KeySubmitResult.MAX_ATTEMPTS -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR,
                            pendingKeyTest = false
                        )
                    }
                    OBDProtocol.KeySubmitResult.REJECTED -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR,
                            pendingKeyTest = false
                        )
                    }
                }
            } else {
                // SHVCS clear flow: original unlock + clear sequence
                val result = OBDProtocol.executeUnlockAndClear(elm, upperKey, createListener())

                when (result) {
                    OBDProtocol.KeySubmitResult.SUCCESS -> {
                        saveKey(upperKey)
                    }
                    OBDProtocol.KeySubmitResult.INVALID_KEY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Enter security key"
                        )
                    }
                    OBDProtocol.KeySubmitResult.TIME_DELAY -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.AWAITING_KEY,
                            progressStep = "Wait then retry"
                        )
                    }
                    OBDProtocol.KeySubmitResult.MAX_ATTEMPTS -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR
                        )
                    }
                    OBDProtocol.KeySubmitResult.REJECTED -> {
                        _state.value = _state.value.copy(
                            connectionState = ConnectionState.ERROR
                        )
                    }
                }
            }
        }
    }

    /**
     * Cancel key input and return to connected state.
     */
    fun cancelKeyInput() {
        _state.value = _state.value.copy(
            connectionState = ConnectionState.CONNECTED,
            progressStep = "",
            progress = 0f,
            errorMessage = null
        )
    }

    fun deleteKey(key: String) {
        val updated = _state.value.savedKeys.filter { it != key }
        _state.value = _state.value.copy(savedKeys = updated)
        prefs.edit().putStringSet("saved_keys", updated.toSet()).apply()
    }

    fun clearLogs() {
        _state.value = _state.value.copy(logs = emptyList())
    }

    fun selectTab(tab: Int) {
        _state.value = _state.value.copy(selectedTab = tab)
    }

    /**
     * Execute a full battery scan via HPCM2.
     * Configures CAN for HPCM2 header, reads all battery PIDs, and parses data.
     */
    fun scanBattery() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        if (_state.value.isBatteryScanLoading) return

        viewModelScope.launch {
            _state.value = _state.value.copy(
                isBatteryScanLoading = true,
                errorMessage = null,
                logs = _state.value.logs + "" + "━━━ STARTING BATTERY SCAN ━━━"
            )

            val batteryListener = object : BatteryScanner.Listener {
                override fun onLog(message: String) {
                    _state.value = _state.value.copy(logs = _state.value.logs + message)
                }
                override fun onProgress(step: Int, totalSteps: Int, description: String) {
                    _state.value = _state.value.copy(
                        progress = step.toFloat() / totalSteps.toFloat(),
                        progressStep = description
                    )
                }
                override fun onBatteryData(data: BatteryDataParser.BatteryData) {
                    _state.value = _state.value.copy(batteryData = data)
                }
                override fun onError(error: String) {
                    _state.value = _state.value.copy(
                        errorMessage = error,
                        logs = _state.value.logs + "✗ Battery scan error: $error"
                    )
                }
            }

            BatteryScanner.scanBattery(elm, batteryListener)

            // Auto-save scan result to Room DB
            val bd = _state.value.batteryData
            if (bd != null) {
                val scanResult = ScanResult(
                    socDisplayed = bd.socDisplayed,
                    socRaw = bd.socRaw,
                    evRange = bd.evRange,
                    hvVoltage = bd.hvVoltage,
                    hvAmperage = bd.hvAmperage,
                    hvPower = bd.hvPower,
                    batteryTemp = bd.batteryTemp,
                    ambientTemp = bd.ambientTemp,
                    capacity = bd.capacityAh,
                    isolation = bd.isolationKohm,
                    cellDelta = bd.cellDelta,
                    chargerAcPower = bd.chargerAcPower,
                    chargerHvPower = bd.chargerHvPower,
                    cellVoltages = bd.cellVoltages,
                    heaterOn = bd.activeHeating,
                    coolingOn = bd.activeCooling,
                    heaterPower = bd.batteryHeaterPower,
                    voltage12v = _state.value.voltage,
                    odometerKm = bd.odometerKm,
                    vehicleSpeed = bd.vehicleSpeed,
                    engineRpm = bd.engineRpm,
                    coolantTemp = bd.coolantTemp,
                    chargerTemp1 = bd.chargerTemp1,
                    chargerTemp2 = bd.chargerTemp2
                )
                db.scanResultDao().insert(scanResult)
                _state.value = _state.value.copy(
                    logs = _state.value.logs + "✓ Scan saved to history"
                )
            }

            _state.value = _state.value.copy(
                isBatteryScanLoading = false,
                progressStep = if (_state.value.batteryData != null) "Battery scan complete" else "Battery scan failed"
            )
        }
    }

    fun selectCompareScanA(scan: ScanResult) {
        _state.value = _state.value.copy(compareScanA = scan)
    }

    fun selectCompareScanB(scan: ScanResult) {
        _state.value = _state.value.copy(compareScanB = scan)
    }

    fun deleteScan(scan: ScanResult) {
        viewModelScope.launch {
            db.scanResultDao().delete(scan)
        }
    }

    fun deleteAllScans() {
        viewModelScope.launch {
            db.scanResultDao().deleteAll()
        }
    }

    /**
     * Start live monitoring — polls battery data continuously.
     */
    fun startLiveMonitoring() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        if (_state.value.isMonitoring) return

        _state.value = _state.value.copy(
            isMonitoring = true,
            liveHistory = emptyList(),
            logs = _state.value.logs + "" + "━━━ STARTING LIVE MONITORING ━━━"
        )

        val listener = object : LiveMonitor.Listener {
            override fun onLog(message: String) {
                _state.value = _state.value.copy(logs = _state.value.logs + message)
            }
            override fun onError(error: String) {
                _state.value = _state.value.copy(
                    logs = _state.value.logs + "✗ Live error: $error"
                )
            }
        }

        liveJob = viewModelScope.launch {
            LiveMonitor.start(elm, LiveMonitor.Config(), listener).collect { point ->
                val history = _state.value.liveHistory.toMutableList()
                history.add(point)
                // Trim to max size
                while (history.size > 300) history.removeAt(0)

                _state.value = _state.value.copy(
                    batteryData = point.data,
                    liveHistory = history
                )
            }
        }
    }

    /**
     * Stop live monitoring.
     */
    fun stopLiveMonitoring() {
        liveJob?.cancel()
        liveJob = null
        _state.value = _state.value.copy(
            isMonitoring = false,
            logs = _state.value.logs + "━━━ LIVE MONITORING STOPPED ━━━"
        )
    }

    /**
     * Read all DTCs from the ECU (requires connection).
     */
    fun readDtcs() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            _state.value = _state.value.copy(
                isDtcLoading = true,
                errorMessage = null,
                dtcList = emptyList()
            )
            OBDProtocol.readAllDtcs(elm, createListener())
            _state.value = _state.value.copy(isDtcLoading = false)
        }
    }

    /**
     * Clear DTCs using OBD-II Mode 04 (generic, no security needed), then re-read.
     */
    fun clearDtcsGeneric() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            _state.value = _state.value.copy(
                isDtcLoading = true,
                errorMessage = null,
                pendingDtcClear = false
            )

            val ok = OBDProtocol.clearAllDtcsGeneric(elm, createListener())

            // Re-read to verify
            kotlinx.coroutines.delay(1000)
            OBDProtocol.readAllDtcs(elm, createListener())

            if (ok) {
                if (_state.value.dtcList.isEmpty()) {
                    _state.value = _state.value.copy(
                        ecuResponse = "✓ Generic DTCs cleared!",
                        ecuResponseCategory = UdsResponse.Category.SUCCESS
                    )
                } else {
                    _state.value = _state.value.copy(
                        ecuResponse = "${_state.value.dtcList.size} DTC(s) remain",
                        ecuResponseCategory = UdsResponse.Category.WARNING
                    )
                }
            } else {
                _state.value = _state.value.copy(
                    ecuResponse = "Generic DTC clear failed",
                    ecuResponseCategory = UdsResponse.Category.ERROR
                )
            }
            _state.value = _state.value.copy(isDtcLoading = false)
        }
    }

    /**
     * Clear DTCs using UDS Service 0x14 on HCPM2 (requires security access).
     * Uses seed-key mappings for auto-submit, or shows key dialog.
     */
    fun clearDtcsUds() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            _state.value = _state.value.copy(
                isDtcLoading = true,
                errorMessage = null,
                pendingDtcClear = true
            )

            // Request seed on HCPM2
            val seed = OBDProtocol.requestSeedForDtcClear(elm, createListener())

            if (seed != null) {
                // Look up key in saved mappings
                val knownKey = _state.value.seedKeyMap[seed.uppercase()]
                if (knownKey != null) {
                    // Auto-submit: key found in mappings
                    _state.value = _state.value.copy(
                        logs = _state.value.logs + "✓ Found saved key for seed $seed → auto-submitting for DTC clear"
                    )
                    val result = OBDProtocol.clearAllDtcsUds(elm, knownKey, createListener())
                    if (result == OBDProtocol.KeySubmitResult.SUCCESS) {
                        saveKey(knownKey)
                    }

                    // Re-read to verify
                    kotlinx.coroutines.delay(1000)
                    OBDProtocol.readAllDtcs(elm, createListener())

                    if (_state.value.dtcList.isEmpty()) {
                        _state.value = _state.value.copy(
                            ecuResponse = "✓ UDS DTCs cleared!",
                            ecuResponseCategory = UdsResponse.Category.SUCCESS
                        )
                    } else {
                        _state.value = _state.value.copy(
                            ecuResponse = "${_state.value.dtcList.size} DTC(s) remain",
                            ecuResponseCategory = UdsResponse.Category.WARNING
                        )
                    }
                    _state.value = _state.value.copy(isDtcLoading = false, pendingDtcClear = false)
                } else {
                    // No key found — try universal generator
                    val generated = SeedKeyGenerator.generateKey(seed)
                    
                    _state.value = _state.value.copy(
                        connectionState = ConnectionState.AWAITING_KEY,
                        seed = seed,
                        progressStep = if (generated != null) "Press RUN again to unlock" else "Enter security key for DTC clear",
                        isDtcLoading = false,
                        autoGeneratedKey = generated,
                        logs = if (generated != null) _state.value.logs + "✓ Universal generator found key: $generated" else _state.value.logs
                    )
                    // submitKey() will handle the rest when pendingDtcClear=true
                }
            } else {
                // Seed request failed
                _state.value = _state.value.copy(
                    isDtcLoading = false,
                    pendingDtcClear = false,
                    ecuResponse = "UDS DTC clear failed — could not get seed",
                    ecuResponseCategory = UdsResponse.Category.ERROR
                )
            }
        }
    }

    /**
     * Scan DTCs from all ECU modules using UDS Service 19 02 (multi-module).
     */
    fun scanDtcsMultiModule() {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            _state.value = _state.value.copy(
                isDtcLoading = true,
                errorMessage = null,
                dtcScanResult = null
            )
            
            val listener = object : DtcScanner.Listener {
                override fun onLog(message: String) {
                    _state.value = _state.value.copy(logs = _state.value.logs + message)
                }
                override fun onProgress(step: Int, totalSteps: Int, description: String) {
                    _state.value = _state.value.copy(
                        progressStep = description,
                        currentStep = step,
                        totalSteps = totalSteps,
                        progress = step.toFloat() / totalSteps
                    )
                }
                override fun onModuleScanned(module: DtcScanner.ModuleDtcs) {
                    // Update result incrementally
                    val current = _state.value.dtcScanResult
                    val modules = (current?.modules ?: emptyList()) + module
                    _state.value = _state.value.copy(
                        dtcScanResult = DtcScanner.DtcScanResult(
                            modules = modules,
                            totalDtcCount = modules.sumOf { it.dtcs.size }
                        )
                    )
                }
                override fun onScanComplete(result: DtcScanner.DtcScanResult) {
                    _state.value = _state.value.copy(
                        dtcScanResult = result,
                        // Also update legacy dtcList with all DTCs flattened
                        dtcList = result.modules.flatMap { it.dtcs }
                    )
                }
                override fun onError(error: String) {
                    _state.value = _state.value.copy(
                        errorMessage = error,
                        logs = _state.value.logs + "✗ ERROR: $error"
                    )
                }
            }
            
            DtcScanner.scanAllModules(elm, listener)
            _state.value = _state.value.copy(isDtcLoading = false)
        }
    }

    /**
     * Clear DTCs on a specific module using UDS Service 14, then rescan that module.
     */
    fun clearModuleDtcs(moduleId: String, moduleName: String) {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            _state.value = _state.value.copy(
                clearingModuleId = moduleId,
                errorMessage = null
            )
            
            val listener = object : DtcScanner.Listener {
                override fun onLog(message: String) {
                    _state.value = _state.value.copy(logs = _state.value.logs + message)
                }
                override fun onProgress(step: Int, totalSteps: Int, description: String) {}
                override fun onModuleScanned(module: DtcScanner.ModuleDtcs) {}
                override fun onScanComplete(result: DtcScanner.DtcScanResult) {}
                override fun onError(error: String) {
                    _state.value = _state.value.copy(
                        errorMessage = error,
                        logs = _state.value.logs + "✗ ERROR: $error"
                    )
                }
            }
            
            val success = DtcScanner.clearModuleDtcs(elm, moduleId, moduleName, listener)
            
            if (success) {
                _state.value = _state.value.copy(
                    ecuResponse = "✓ DTCs cleared on $moduleName!",
                    ecuResponseCategory = UdsResponse.Category.SUCCESS,
                    logs = _state.value.logs + "✓ DTCs cleared on $moduleName — rescanning..."
                )
                
                // Rescan all modules to refresh
                kotlinx.coroutines.delay(1000)
                _state.value = _state.value.copy(clearingModuleId = null, isDtcLoading = true)
                DtcScanner.scanAllModules(elm, listener)
                _state.value = _state.value.copy(isDtcLoading = false)
            } else {
                _state.value = _state.value.copy(
                    ecuResponse = "Clear failed on $moduleName",
                    ecuResponseCategory = UdsResponse.Category.ERROR,
                    clearingModuleId = null
                )
            }
        }
    }

    private fun createListener() = object : OBDProtocol.Listener {
        override fun onLog(message: String) {
            _state.value = _state.value.copy(logs = _state.value.logs + message)
        }
        override fun onVinReceived(vin: String) {
            _state.value = _state.value.copy(vin = vin)
        }
        override fun onVoltageReceived(voltage: String) {
            _state.value = _state.value.copy(voltage = voltage)
        }
        override fun onSeedReceived(seed: String) {
            _state.value = _state.value.copy(seed = seed)
        }
        override fun onProgress(step: Int, totalSteps: Int, description: String) {
            _state.value = _state.value.copy(
                progress = step.toFloat() / totalSteps.toFloat(),
                currentStep = step, totalSteps = totalSteps,
                progressStep = description
            )
        }
        override fun onAwaitingKey(seed: String) {
            // Check for auto-submit: if we have a known key for this seed
            val knownKey = _state.value.seedKeyMap[seed.uppercase()]
            if (knownKey != null) {
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.AWAITING_KEY,
                    progressStep = "Auto-submitting key for seed $seed",
                    logs = _state.value.logs + "✓ Found saved key for seed $seed → auto-submitting"
                )
                // Auto-submit the key
                submitKey(knownKey)
            } else {
                val generated = SeedKeyGenerator.generateKey(seed)
                
                _state.value = _state.value.copy(
                    connectionState = ConnectionState.AWAITING_KEY,
                    progressStep = if (generated != null) "Press SUBMIT to unlock" else "Enter security key",
                    autoGeneratedKey = generated,
                    logs = if (generated != null) _state.value.logs + "✓ Universal generator found key: $generated" else _state.value.logs
                )
            }
        }
        override fun onUnlockSuccess() {
            _state.value = _state.value.copy(
                logs = _state.value.logs + "✓ HCPM2 Unlocked"
            )
        }
        override fun onClearSuccess() {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.SUCCESS,
                progress = 1f,
                progressStep = "SHVCS ERROR CLEARED!"
            )
        }
        override fun onClearFailed(reason: String) {
            _state.value = _state.value.copy(
                connectionState = ConnectionState.ERROR,
                errorMessage = reason
            )
        }
        override fun onError(error: String) {
            // Only log the error — don't change connection state
            // (connection state is managed by the calling functions)
            _state.value = _state.value.copy(
                errorMessage = error,
                logs = _state.value.logs + "✗ ERROR: $error"
            )
        }
        override fun onEcuResponse(response: UdsResponse) {
            _state.value = _state.value.copy(
                ecuResponse = response.toDisplayString(),
                ecuResponseCategory = response.category()
            )
        }
        override fun onDtcsRead(dtcs: List<DtcParser.DtcCode>) {
            _state.value = _state.value.copy(dtcList = dtcs)
        }
        override fun onEcusDiscovered(ecus: List<OBDProtocol.DiscoveredEcu>) {
            _state.value = _state.value.copy(discoveredEcus = ecus)
        }
    }

    private fun saveKey(key: String) {
        val existing = _state.value.savedKeys.toMutableList()
        existing.remove(key) // Remove if exists to put at top
        existing.add(0, key) // Add at top
        if (existing.size > 10) existing.removeAt(existing.lastIndex)
        _state.value = _state.value.copy(savedKeys = existing)
        prefs.edit().putStringSet("saved_keys", existing.toSet()).apply()
    }

    private fun loadSavedKeys(): List<String> {
        return prefs.getStringSet("saved_keys", emptySet())?.toList() ?: emptyList()
    }

    private fun loadSeedKeyMap(): Map<String, String> {
        val json = prefs.getString("seed_key_map", null) ?: return emptyMap()
        return try {
            val obj = JSONObject(json)
            val map = mutableMapOf<String, String>()
            obj.keys().forEach { key -> map[key] = obj.getString(key) }
            map
        } catch (_: Exception) { emptyMap() }
    }

    private fun persistSeedKeyMap(map: Map<String, String>) {
        val obj = JSONObject()
        map.forEach { (seed, key) -> obj.put(seed, key) }
        prefs.edit().putString("seed_key_map", obj.toString()).apply()
    }

    /**
     * Send a raw command to the ELM327, optionally setting a target ECU header first.
     */
    fun sendRawCommand(command: String, ecuHeader: String? = null) {
        if (_state.value.connectionState == ConnectionState.DISCONNECTED) return
        viewModelScope.launch {
            try {
                val history = _state.value.consoleHistory.toMutableList()

                // Set header if specified
                if (!ecuHeader.isNullOrBlank()) {
                    val shCmd = "ATSH$ecuHeader"
                    history.add(shCmd to "...")
                    _state.value = _state.value.copy(consoleHistory = history.toList())

                    val shResult = elm.sendCommand(shCmd, timeoutMs = 3000L)
                    shResult.onSuccess { resp ->
                        history[history.lastIndex] = shCmd to resp.trim()
                    }.onFailure { e ->
                        history[history.lastIndex] = shCmd to "ERROR: ${e.message}"
                    }
                    _state.value = _state.value.copy(
                        consoleHistory = history.toList(),
                        logs = _state.value.logs + "► CONSOLE: $shCmd → ${history.last().second}"
                    )
                    kotlinx.coroutines.delay(100)
                }

                // Send the actual command
                history.add(command to "...")
                _state.value = _state.value.copy(consoleHistory = history.toList())

                val result = elm.sendCommand(command, timeoutMs = 10000L)
                result.onSuccess { resp ->
                    history[history.lastIndex] = command to resp.trim()
                }.onFailure { e ->
                    history[history.lastIndex] = command to "ERROR: ${e.message}"
                }
                _state.value = _state.value.copy(
                    consoleHistory = history.toList(),
                    logs = _state.value.logs + "► CONSOLE: $command → ${history.last().second}"
                )

            } catch (e: Exception) {
                _state.value = _state.value.copy(
                    logs = _state.value.logs + "✗ Console error: ${e.message}"
                )
            }
        }
    }

    fun clearConsoleHistory() {
        _state.value = _state.value.copy(consoleHistory = emptyList())
    }

    override fun onCleared() {
        super.onCleared()
        viewModelScope.launch { elm.disconnect() }
    }
}
